version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "test:1:1"
  producer:
    build: ./producer
    depends_on:
      - kafka
    environment:
      TOPIC: test
      BOOTSTRAP_SERVERS: kafka:9092
  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - producer
    environment:
      TOPIC: test
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: foo
