name: Deploy Consumer

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  build-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DIGITALOCEAN_REGISTRY }}
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Export release tag
        run: echo "RELEASE_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - uses: docker/build-push-action@v2
        with:
          context: ./app/consumer
          push: true
          tags: ${{ secrets.DIGITALOCEAN_REGISTRY }}/kafka-consumer:${{ env.RELEASE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Configure kubectl
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.K8S_CLUSTER_NAME }}
      - name: Export release tag
        run: echo "RELEASE_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Update k8s manifest
        run: |
          sed -i '/image:/s/:latest/:${{ env.RELEASE_TAG }}/' app/consumer/deploy.yaml
      - run: kubectl apply -f app/consumer/deploy.yaml
      - run: |
          kubectl rollout status deployment/kafka-consumer \
            -n ${{ secrets.KAFKA_NAMESPACE }} \
            --timeout 5m
