name: Terraform

on:
  pull_request:
    branches:
      - main

jobs:
  changed:
    runs-on: ubuntu-latest
    outputs:
      infra: ${{ steps.changed.outputs.infra }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Git diff
        id: changed
        run: |
          echo "::set-output name=infra::$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- infra | tr -d '\n')"
  lint:
    runs-on: ubuntu-latest
    needs: changed
    if: ${{ needs.changed.outputs.infra }}
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
